CUDA_VISIBLE_DEVICES=0 python ./src/export_model.py \
    --model_name_or_path /home/dyf/model/Llama-2-7b-chat-hf-modified \
    --adapter_name_or_path /home/finetune/rog_240429_02 \
    --template self_rog_llama2 \
    --finetuning_type lora \
    --export_dir /home/dyf/model/rog_240429 \
    --export_size 10 \
    --export_device cuda \
    --export_legacy_format False \
    --resize_vocab True \
    --split_special_tokens True \
    --use_fast_tokenizer False
