CUDA_VISIBLE_DEVICES=0 llamafactory-cli export \
    --model_name_or_path /home/lx/models/Llama-2-7b-chat-hf \
    --adapter_name_or_path /home/lx/models/sft/rog_240516 \
    --template llama2_self \
    --finetuning_type lora \
    --export_dir /home/lx/models/rog_240516 \
    --export_size 10 \
    --export_device cuda \
    --export_legacy_format False \
    --resize_vocab True \
    --split_special_tokens True \
    --use_fast_tokenizer False
